"""add user lang

Revision ID: 5afd6169c478
Revises: 1c5f6081ed72
Create Date: 2026-03-20 17:36:55.271719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from backend.core.constants.core import AppLang


# revision identifiers, used by Alembic.
revision: str = '5afd6169c478'
down_revision: Union[str, Sequence[str], None] = '1c5f6081ed72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lang', sa.String(), nullable=False, server_default=AppLang.RU))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lang')
    # ### end Alembic commands ###
